services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/custom.conf:ro
    depends_on:
      - cli
      - srv
    networks:
      - app-network
    restart: unless-stopped

  cli:
    build: ./cli
    expose:
      - "80"
    depends_on:
      - srv
    environment:
      - VUE_APP_API_URL=http://api.localhost
      - VITE_APP_BASE_URL=http://localhost
    networks:
      - app-network
    restart: unless-stopped

  srv:
    build: ./srv
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - MONGO_URI=mongodb://root:secret@mongo:27017
      - PRODUCTION=true
      - FRONTEND_URL="http://localhost/"
    networks:
      - app-network
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "222:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
